# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f44bf1abf401387f61fbeb3226cd66d2f3354d4d9f0847b893f1e25f5b7b8b89d1724d050706773b46d1584e875b54fdb68c673046de2ae482fb611440021fd8

test:
  secret_key_base: 27ae8b39240f076cb5e5d8a9436678107e9aaabd88b4d45f13a1887f6c4f5793f8e1df451c4b486b30114f23dcb0219e449cc6ae0e20c6c69d0a262c16a2c6a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
